version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=mikesudirman.me
      - LETSENCRYPT_HOST=mikesudirman.me
    networks:
      - proxy

    

networks:
  proxy:
    external:
      name: proxy