version: "3"
services:
  web:
    build: .
    ports:
      - "3001:80"
    environment:
      - VIRTUAL_HOST=michaelsudirman.com
      - LETSENCRYPT_HOST=michaelsudirman.com
    networks:
      - proxy

    

networks:
  proxy:
    external:
      name: proxy