version: "3"
services:
  web:
    build: .
      # context: ./client
      # dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - VIRTUAL_HOST=mikesudirman.me
      - LETSENCRYPT_HOST=mikesudirman.me
    networks:
      - proxy

    

networks:
  proxy:
    external:
      name: proxy